### ISSUE TITLE
Blender crashes

### ISSUE THREAD

**Issue by mifth** [friedererdmann/blender_pyside2_example#1]
Hi, Blender crashes when I press the pyside button. I tested blender 2.93 and 3.0. I assume this is because of the copied context.

**Comment by hanWolf3D** [comment]
blender crashes for me too on 3.0 when clicking create camera

**Comment by MatinFalahmanesh** [comment]
same...

**Comment by hanWolf3D** [comment]
got it to work by changing the camera code
the UI works, but blender has updated so the camera select code causes a crash

if you only care about the pyside sample, you can comment out the camera code and replace it with a
```print('hello world')``` and it'll work

**Comment by mifth** [comment]
I assume there will be no sense in the plugin if you comment the camera code. That should be a bridge between pyside and blender.

Btw, I have a different approach to this I did it in my own Rune addon. I'll post my example on BlenderStackOverflow and let you know here.

**Comment by mifth** [comment]
Apologies for a delay. Here is a simple example how to use Pyside6.
https://blender.stackexchange.com/a/325520/911
